# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Main' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Main
  pod 'Common', :path => '../Common'
  pod 'FeatureA', :path => '../Features/FeatureA'
  pod 'FeatureB', :path => '../Features/FeatureB'

  pod 'Swinject', '2.5.0'
  pod 'SwinjectAutoregistration', '2.5.1'
  pod 'RxSwift', '4.4.1'
  pod 'RxCocoa', '4.4.1'
  pod 'RxSwiftExt', '3.4.0'

  target 'MainTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '1.3.4'
    pod 'Nimble', '7.3.4'
    pod 'RxTest', '4.4.1'
  end

end
