use_frameworks!

target 'FeatureA_Example' do
  pod 'FeatureA', :path => '../'
  pod 'Common', :path => '../../../Common'

  pod 'RxSwift', '4.4.1'
  pod 'RxCocoa', '4.4.1'
  pod 'RxSwiftExt', '3.4.0'

  target 'FeatureA_Tests' do
    inherit! :search_paths

    pod 'Quick', '1.3.4'
    pod 'Nimble', '7.3.4'
    pod 'RxTest', '4.4.1'
  end
end
